2019-06-26 11:41:31,981 INFO: Microblog startup [in C:\Users\Omar\PycharmProjects\microblog\app\__init__.py:47]
2019-06-26 11:42:43,283 INFO: Microblog startup [in C:\Users\Omar\PycharmProjects\microblog\app\__init__.py:47]
2019-06-26 11:42:52,636 INFO: Microblog startup [in C:\Users\Omar\PycharmProjects\microblog\app\__init__.py:47]
2019-06-26 11:43:26,102 INFO: Microblog startup [in C:\Users\Omar\PycharmProjects\microblog\app\__init__.py:47]
2019-06-26 11:43:40,140 INFO: Microblog startup [in C:\Users\Omar\PycharmProjects\microblog\app\__init__.py:47]
2019-06-26 13:31:52,271 INFO: Microblog startup [in C:\Users\Omar\PycharmProjects\microblog\app\__init__.py:47]
2019-06-26 13:33:07,978 INFO: Microblog startup [in C:\Users\Omar\PycharmProjects\microblog\app\__init__.py:47]
2019-06-26 13:33:09,680 ERROR: Exception on /login [GET] [in C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Omar\PycharmProjects\microblog\app\routes.py", line 71, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Omar\PycharmProjects\microblog\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\Omar\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
2019-06-28 15:44:10,481 INFO: Microblog startup [in C:\Users\Omar\PycharmProjects\microblog\app\__init__.py:47]
